

CREATE TABLE regions(
	REGION_id INT PRIMARY KEY,
	REGION_name varchar(25)
);


CREATE TABLE departments(
	DEPARTMENT_ID INT PRIMARY KEY,
	DEPARTMENT_NAME VARCHAR(30),
	MANAGER_ID INT,
	LOCATION_ID INT
);


CREATE TABLE countries(
	COUNTRIES_ID CHAR(2) PRIMARY KEY,
	COUNTRIES_NAME VARCHAR(40),
	REGION_ID INT,

	FOREIGN KEY(REGION_ID)
	REFERENCES regions(REGION_ID)
);


CREATE TABLE locations(
	LOCATION_ID INT PRIMARY KEY,
	STREET_ADDRESS VARCHAR(25),
	POSTAL_CODE VARCHAR(12),
	CITY VARCHAR(30),
	STATE_PROVINCE VARCHAR(12),
	COUNTRIES_ID CHAR(2),


	FOREIGN KEY(COUNTRIES_ID)
	REFERENCES countries (COUNTRIES_ID)
);


CREATE TABLE jobs(
	JOB_ID VARCHAR(10) PRIMARY KEY,
	JOP_TITLE VARCHAR(35),
	MIN_SALARY INT,
	MAX_SALARY INT
);


CREATE TABLE jop_grades(
	GRADE_LEVEL VARCHAR(2) PRIMARY KEY,
	LOWEST_SAL INT,
	HIGHEST_SAL INT
);


CREATE TABLE jop_history(
	EMPLOYEE_ID INT PRIMARY KEY,
	START_DATE DATE,
	END_DATE DATE,
	JOB_ID VARCHAR(10),
	DEPARTMENT_ID INT,

	FOREIGN KEY(DEPARTMENT_ID)
	REFERENCES departments (DEPARTMENT_ID),

	FOREIGN KEY(JOB_ID)
	REFERENCES jobs (JOB_ID),
);


CREATE TABLE employees(
	EMPLOYEE_ID INT PRIMARY KEY,
	FIRST_NAME VARCHAR(20),
	LAST_NAME VARCHAR(25),
	EMAIL VARCHAR(25),
	PHONE_NUMBER VARCHAR(20),
	HIRE_DATE DATE,
	JOB_ID VARCHAR(10),
	SALARY INT,
	COMMISSION_PCT INT,
	MANAGER_ID INT,
	DEPARTMENT_ID INT,

	FOREIGN KEY(JOB_ID)
	REFERENCES jobs (JOB_ID),

	FOREIGN KEY(DEPARTMENT_ID)
	REFERENCES departments (DEPARTMENT_ID),
);